### PR TITLE
Ux improvement

### PR DESCRIPTION
**Pull request by frisi**
various improvements to the user experience.

editors:
* see which notices have been set to inactive in the management-view
* famfamfam icon for controlpanel
* translateable ui

integrators
* hide link is explained by a translateable title attribute
* label for screenreaders
* css-icon can be used instead of label for standard users
* can add css transforms / animations when hiding a notice
* translateable ui

### CODE REVIEW

**Comment by frisi** [comment]
@vipod could you please review/merge my two pull requests (this one bis based on #2)

is it okay to develop in the collective repository?
will you move the package to collective or do you intend to keep it here in softformance?

regards, harald

**Comment by frisi** [comment]
@vipod and @sureshvv - could you please review+merge or tell me what to improve?
please also answer the questions in my comment above

**Comment by frisi** [comment]
hi @vipod and @sureshvv 
could you please answer my questions above. if i don't get any feedback i'll merge the commits to collective master the next time i have to work on this package again.
thanks in advance

**Comment by vipod** [comment]
sorry for detail. somehow I haven't got any notifications in my inbox. merging it now. looks good!

no, we're not going to put it into collective.

**Comment by frisi** [comment]
thanks for merging @vipod 
it looks like my changelogs have accidentally slipped into those of the 1.1 release.

could you please make a new release and/or grant me permissions to this repo and on pypi (username frisi?)

**Comment by vipod** [comment]
Added you in pypi and in github. Please check and apply your updates.

**Comment by frisi** [comment]
@vipod sorry for the delay. just wanted to cut the releases but i don't have permission to write to the repository
could you pleas add me as a member with permission to push?

```
$ git push origin master
ERROR: Permission to softformance/collective.notices.git denied to frisi.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by vipod** [comment]
Hi, I added you as external collaborator few months ago, but can see that invitation is still pending on your side. So, please, check your email, accept it and I believe you'll be able to push and do any read/write actions with collective.notices ;-)

**Comment by frisi** [comment]
sorry @vipod, i missed that mail :-( thanks for the heads up!

**Pull request merged**
